### ISSUE TITLE
update installer scripts

### ISSUE THREAD

**Issue by lufre1** [computational-cell-analytics/micro-sam#505]
## Description
Update installer scripts and make new release.

## ToDo
- [x] disable mac support
- [ ] check source branches
- [x] check triggers (git tags)
- [ ] run workflow
- [ ] check installers

## Solutions
- source branch:
  - as long as nothing is specified, then `default` branch is source branch
    - for now, the `default` branch is `master`
  - here is how to specify a branch:
```yaml
steps:
  - name: Checkout specific branch
    uses: actions/checkout@v4
    with:
      branch: 'feature/my-new-feature'  # Replace with desired branch name
```
or checkout the branch that contains the tagged commit:
```yaml
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} 
```
- triggers:
  - atm any tag triggers the workflow
    - tags 
  - specify pushes to branch as trigger
```yaml
on:
  push:
    branches:
      - 'master'  
    tags:
      - '**'
```
-

**Comment by lufre1** [comment]
@constantinpape is there a preferred behavior that i should implement?

**Comment by constantinpape** [comment]
> @constantinpape is there a preferred behavior that i should implement?

What exactly do you mean?

**Comment by lufre1** [comment]
at the moment it is possible to push a tagged commit on an arbitrary branch to trigger the workflow. The workflow checks out the `default` branch to build the installer which is the `master` branch. This may lead to confusion. 
I provided some approaches to solve this problem in the issue description above.

**Comment by lufre1** [comment]
deprecated node.js in build workflow [see](https://github.com/computational-cell-analytics/micro-sam/actions/runs/8616452984)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: conda-incubator/setup-miniconda@v2, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
windows-latest
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: conda-incubator/setup-miniconda@v2, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by lufre1** [comment]
idea: try to install micro_sam with post_install script:
https://github.com/conda/constructor/issues/515

**Comment by constantinpape** [comment]
Implemented in #510 
(There might be some minor fixes necessary, but these should now be straightforward)
