### ISSUE TITLE
update doc

### ISSUE THREAD

**Issue by lufre1** [computational-cell-analytics/micro-sam#539]
## Description
Update the documentation of micro_sam with regards to the recent changes.
## ToDo

- [ ] check general structure of existing docs (understandability, clarity, findability, ...)
- [x] update in-memory / disk embedding docs
- [x] update docs about loading / saving process
- [x] update tiling docs (quadratic)
- [ ] add/update images?
- [ ] update the "what's new" section (annotation_tools.md > ## Starting via GUI)

**Comment by lufre1** [comment]
Maybe change the un-/collapsible sections buttons to more meaningful names:
- `Settings` (embeddings) -> `Embeddings Settings` (or `Advanced Embeddings Settings`)
- `Settings` (automatic segmentation) -> `Automatic Segmentation Settings`

**Comment by lufre1** [comment]
in annotation_tools.md in section `Known limitations` there is a very specific statement about the tracking annotator (i guess):
> - Prompt bounding boxes do not provide the full functionality for tracking yet (they cannot be used for divisions or for starting new tracks). See also [this github issue](https://github.com/computational-cell-analytics/micro-sam/issues/23).

Does this still hold true?

**Comment by constantinpape** [comment]
You can ignore the `Known limitations` for now, we will integrate this in the new FAQ section.

**Comment by constantinpape** [comment]
The most important things here are taken care of. I am closing this for now, we will take care of the rest as part of #501
